# ========================================
# SimpleMoreSounds - Configuration
# ========================================
# Plugin to add custom sounds to server events
#
# Parameters for each sound:
# - enabled: true/false (enable/disable the sound)
# - sound: name of the sound (see Minecraft sound list)
# - volume: 0.0-1.0 (sound volume)
# - pitch: 0.5-2.0 (sound pitch)

# Sound when a player types in chat
chat_sound:
  enabled: true
  sound: "ENTITY_ITEM_PICKUP"
  volume: 0.5
  pitch: 1.0

# Sound when a player tag someone in chat (Player nickname)
mention_sound:
  enabled: true
  sound: "BLOCK_NOTE_BLOCK_CHIME"
  volume: 1.0
  pitch: 1.5

# Sound when a player send a msg (/msg, /tell..)
private_message_sound:
  enabled: true
  sound: "BLOCK_NOTE_BLOCK_BELL"
  volume: 1.0
  pitch: 1.2

# Sound when a player drops an item
item_drop_sound:
  enabled: true
  sound: "ENTITY_ARROW_SHOOT"
  volume: 0.7
  pitch: 0.8

# Sound when a player dies
death_sound:
  enabled: true
  sound: "ENTITY_PLAYER_DEATH"
  volume: 1.0
  pitch: 1.0

# Sound when a player joins for the first time
first_join_sound:
  enabled: true
  sound: "ENTITY_PLAYER_LEVELUP"
  volume: 1.0
  pitch: 1.2

# Sound when a player connects
join_sound:
  enabled: true
  sound: "BLOCK_NOTE_BLOCK_CHIME"
  volume: 0.8
  pitch: 1.0

# Sound when a player disconnects
quit_sound:
  enabled: true
  sound: "BLOCK_NOTE_BLOCK_BASS"
  volume: 0.8
  pitch: 0.8

# Sound when a player runs a command
command_sound:
  enabled: true
  sound: "UI_BUTTON_CLICK"
  volume: 0.3
  pitch: 1.0

# Sound when a player switches hotbar slot
hotbar_switch_sound:
  enabled: true
  sound: "ITEM_ARMOR_EQUIP_LEATHER"
  volume: 0.2
  pitch: 1.5

# Sound when a player closes inventory
inventory_close_sound:
  enabled: true
  sound: "BLOCK_CHEST_CLOSE"
  volume: 0.6
  pitch: 1.0

# ========================================
# COMBAT SOUNDS
# ========================================

# Sound when a player lands a critical hit
critical_hit_sound:
  enabled: true
  sound: "BLOCK_ENCHANTMENT_TABLE_USE"
  volume: 1.0
  pitch: 1.2

# Sound when a player shoots an arrow
arrow_shoot_sound:
  enabled: true
  sound: "ENCHANT_THORNS_HIT"
  volume: 1.7
  pitch: 1.0

# Sound when a player kills a mob
mob_kill_sound:
  enabled: true
  sound: "PARTICLE_SOUL_ESCAPE"
  volume: 1.1
  pitch: 1.3

# Sound when a player kills another player (PvP)
player_kill_sound:
  enabled: true
  sound: "ENTITY_LIGHTNING_BOLT_THUNDER"
  volume: 0.4
  pitch: 1.5

# ========================================
# INTERACTION SOUNDS
# ========================================

# Sound when a player uses a furnace
furnace_use_sound:
  enabled: true
  sound: "BLOCK_FURNACE_FIRE_CRACKLE"
  volume: 0.6
  pitch: 1.0

# Sound when a player uses a crafting table
crafting_table_use_sound:
  enabled: true
  sound: "BLOCK_WOOD_PLACE"
  volume: 0.5
  pitch: 1.2

# Sound when a player uses an anvil
anvil_use_sound:
  enabled: true
  sound: "BLOCK_ANVIL_USE"
  volume: 0.7
  pitch: 1.0

# Sound when a player uses the enchanting table
enchanting_table_use_sound:
  enabled: true
  sound: "BLOCK_ENCHANTMENT_TABLE_USE"
  volume: 0.8
  pitch: 1.0

# ========================================
# FISHING SOUNDS
# ========================================

# Sound when a player casts the fishing rod
fishing_cast_sound:
  enabled: true
  sound: "ENTITY_FISHING_BOBBER_THROW"
  volume: 0.6
  pitch: 1.0

# Sound when a player catches something fishing
fishing_catch_sound:
  enabled: true
  sound: "ENTITY_FISHING_BOBBER_RETRIEVE"
  volume: 0.8
  pitch: 1.1

# ========================================
# MISCELLANEOUS SOUNDS
# ========================================

# Sound when a tool breaks
tool_break_sound:
  enabled: true
  sound: "UI_TOAST_CHALLENGE_COMPLETE"
  volume: 1.0
  pitch: 0.8

# Sound when a player respawns
player_respawn_sound:
  enabled: true
  sound: "ENTITY_PLAYER_BREATH"
  volume: 0.7
  pitch: 1.0

# Sound when a player teleports
teleport_sound:
  enabled: true
  sound: "ENTITY_ENDERMAN_TELEPORT"
  volume: 0.8
  pitch: 1.2

# ========================================
# INVENTORY SOUNDS
# ========================================

# Sound when a player’s inventory is full
inventory_full_sound:
  enabled: true
  sound: "BLOCK_NOTE_BLOCK_BASS"
  volume: 0.8
  pitch: 0.5

# Sound when a player opens a shulker box
shulker_open_sound:
  enabled: true
  sound: "UI_LOOM_TAKE_RESULT"
  volume: 0.7
  pitch: 1.0

# ========================================
# PROGRESSION SOUNDS
# ========================================

# Sound when a player completes an advancement
advancement_complete_sound:
  enabled: false
  sound: "UI_TOAST_CHALLENGE_COMPLETE"
  volume: 0.5
  pitch: 1.0

# Sound when a player gains experience
experience_gain_sound:
  enabled: true
  sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  volume: 0.3
  pitch: 1.0

  #          SOUND LIST:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html