name: SimpleMoreSounds
version: '1.7'
main: com.Lino.simpleMoreSounds.SimpleMoreSounds
api-version: '1.21'
authors: [Lino9999]
commands:
  soundsreload:
    description: Reload plugin configuration
    aliases: [smsreload]
permissions:
  simplemoresounds.reload:
    description: Permission to reload the plugin
    default: op