name: SimpleMoreSounds
version: '3.0'
main: com.Lino.simpleMoreSounds.SimpleMoreSounds
api-version: '1.21'
author: Lino
commands:
  soundsreload:
    description: Reload plugin configuration
    aliases: [smsreload]
permissions:
  simplemoresounds.reload:
    description: Permission to reload the plugin
    default: op